name: .NET Core

on:
  workflow_dispatch:
    inputs:
      secret_id:
        required: true
      secret_key:
        required: true
      session_token:
        required: true
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
    - name: dotnet Publish
      run: dotnet publish MaskApi/MaskApi.csproj -c Release -o MaskApi -r linux-x64

    - name: Build deployment package
      run: zip -r MaskApi-deploy.zip MaskApi
    
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v13
      with:
        aws_access_key: ${{ github.events.inputs.secret_id }}
        aws_secret_key: ${{ github.events.inputs.secret_key }}
        aws_session_token: ${{ github.events.inputs.session_token }}
        application_name: MaskApi
        environment_name: MaskApi-Environment
        version_label: 12345
        region: us-east-1
        deployment_package: Mask-deploy.zip
