name: .NET Core

on:
  workflow_dispatch:
    inputs:
      secret_id:
        required: true
      secret_key:
        required: true
      session_token:
        required: true
  
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "id: ${{ github.event.inputs.secret_id }}"
        echo "key: ${{ github.event.inputs.secret_key }}" 
        echo "token: ${{ github.event.inputs.session_token }}" 

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
#    - name: dotnet Publish
#      run: dotnet publish MaskApi/MaskApi.csproj -c Release -o MaskApi -r linux-x64 --self-contained true

#    - name: Build deployment package
#     run: zip -r MaskApi-deploy.zip MaskApi
    
    - name: Deploy to EB
      run: dotnet eb deploy-environment --aws-access-key-id ${{ github.event.inputs.secret_id }} --aws-secret-key ${{ github.event.inputs.secret_key }} --aws-session-token ${{ github.event.inputs.session_token }} -app MaskApi -env MaskApi-Environment --region us-east-1
